# Generated by Django 4.0.6 on 2022-08-12 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_encodings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('detection_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 8, 12, 18, 29, 58, 302145, tzinfo=utc))),
                ('unknown', models.BooleanField(default=True)),
            ],
        ),
    ]
